# Generated by Django 4.2.14 on 2024-07-21 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_author_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
